syslog-ng-cfg-db.py: Fix Exception: Keyword without resolvation: KW_UPPER
This keyword seems to be missing.  Same issue with KW_LOWER. Might have
been forgotten in ca3821f45e4855c171ebde1210cb44aa1fd37e98.

```
romain@desktop-fln40kq ~/Projects/syslog-ng % ./contrib/config_option_database/syslog-ng-cfg-db.py
Traceback (most recent call last):
  File "/home/romain/Projects/syslog-ng/contrib/config_option_database/utils/OptionParser.py", line 123, in _resolve_token
    return '/'.join(sorted(db[token]))
KeyError: 'KW_UPPER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/romain/Projects/syslog-ng/./contrib/config_option_database/syslog-ng-cfg-db.py", line 272, in <module>
    main()
  File "/home/romain/Projects/syslog-ng/./contrib/config_option_database/syslog-ng-cfg-db.py", line 266, in main
    db = _get_db(rebuild=args.rebuild)
  File "/home/romain/Projects/syslog-ng/./contrib/config_option_database/syslog-ng-cfg-db.py", line 135, in _get_db
    db = _build_db()
  File "/home/romain/Projects/syslog-ng/./contrib/config_option_database/syslog-ng-cfg-db.py", line 91, in _build_db
    options = get_driver_options()
  File "/home/romain/Projects/syslog-ng/contrib/config_option_database/utils/ConfigOptions.py", line 90, in get_driver_options
    options |= path_to_options(path)
  File "/home/romain/Projects/syslog-ng/contrib/config_option_database/utils/OptionParser.py", line 153, in path_to_options
    options.add(_resolve_option(context, driver, keyword, arguments, parents))
  File "/home/romain/Projects/syslog-ng/contrib/config_option_database/utils/OptionParser.py", line 140, in _resolve_option
    keyword = _resolve_token(keyword)
  File "/home/romain/Projects/syslog-ng/contrib/config_option_database/utils/OptionParser.py", line 126, in _resolve_token
    raise Exception('Keyword without resolvation: ' + token)
Exception: Keyword without resolvation: KW_UPPER
```

Signed-off-by: Romain Tartière <romain@blogreen.org>