loggen_helper: add missing libraries
loggen_helper is intended to be a library. It contains openssl related
code. Hence it needs to link to openssl.

This fixes the following case: openssl 1.0.2 is installed on system,
openssl1.1.1 installed on nonstandard location, that is fed to
syslog-ng by PKG_CONFIG_PATH.

During compiling test_loggen_filereader, we link to loggen_helper,
that only transitively links to openssl. This means it will link
to openssl1.1.1, but will use 1.0.2 headers from system.

This results in a compile error:
```
tests/loggen/libloggen_helper.a(loggen_helper.c.o): In function `open_ssl_connection':
/home/furiel/workspace/test-syslogng/syslog-ng/tests/loggen/loggen_helper.c:256: undefined reference to `SSLv23_client_method'
```

If proper 1.1.1 headers were used, `SSLv23_client_method` would be a
`#define` for `TLS_client_method`, and everything would compile correctly.

Signed-off-by: Antal Nemes <antal.nemes.hu@gmail.com>