filterx: rename internal isset field to is_set
It can conflict with a macro:

In file included from ../lib/filterx/expr-function.h:27,
                 from ../lib/filterx/object-datetime.h:27,
                 from ../modules/grpc/otel/filterx/protobuf-field.cpp:28:
../lib/filterx/filterx-expr.h:124:28: error: macro "isset" requires 2 arguments, but only 1 given
  124 |     return self->isset(self);
      |                            ^
In file included from /usr/include/google/protobuf/io/coded_stream.h:134,
                 from ./modules/grpc/protos/otlp/opentelemetry/proto/logs/v1/logs.pb.h:23,
                 from ../modules/grpc/otel/filterx/protobuf-field.hpp:32,
                 from ../modules/grpc/otel/filterx/protobuf-field.cpp:23:
/usr/include/x86_64-linux-gnu/sys/param.h:85: note: macro "isset" defined here
   85 | #define isset(a,i)      ((a)[(i)/NBBY] & (1<<((i)%NBBY)))
      |

Signed-off-by: Attila Szakacs <attila.szakacs@axoflow.com>