fixed compilation error because of a bogus forward-port of the last HP-UX fix
/home/bazsi/zwa/work/syslog-ng-ose-3.0/syslog-ng-ose/src/logwriter.c: In function ‘log_writer_fd_dispatch’:
/home/bazsi/zwa/work/syslog-ng-ose-3.0/syslog-ng-ose/src/logwriter.c:241: error: ‘LogWriterWatch’ has no member named ‘fd’