msg_format_inject_parse_error: new function to format a "parse-error" message
Instead of open coding this in syslogformat and linux-kmsg-format, centralize
the functionality here.

Was changed somewhat to use log_msg_clear()

Signed-off-by: Balazs Scheidler <bazsi@balabit.hu>